[package]
name = "yua-osd"
description = "YUA OS Manager daemon — acesso privilegiado auditável ao hardware"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "yua-osd"
path = "src/main.rs"

[dependencies]
yua-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
libc.workspace = true
